name: revenuecat_sample
description: RevenueCat Sample Code

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  purchases_flutter: ^3.9.5
  webview_flutter: ^3.0.0
  adaptive_dialog: ^1.3.0

flutter:
  uses-material-design: true
